### ISSUE TITLE
Instander for Instagram

### ISSUE THREAD

**Issue by matbonucci** [mendel5/alternative-front-ends#104]
https://thedise.me/instander/repo/
Not open source, just the Instagram app without ads, download content and other perks

**Comment by NoPlagiarism** [comment]
> Overview of alternative open source front-ends

Instander is good. I'm using it. but... Read readme..

**Comment by NoPlagiarism** [comment]
(and close issue pls)

**Comment by HookedBehemoth** [comment]
Nothing to add here.
Not open source.
