### ISSUE TITLE
Add youtube-local

### ISSUE THREAD

**Issue by ghplpt** [mendel5/alternative-front-ends#13]
Name: youtube-local
Site: https://github.com/user234683/youtube-local
About: browser-based client for watching Youtube anonymously and with greater page performance

**Comment by mendel5** [comment]
Thanks for your contribution!

I just added youtube-local.

Commit: https://github.com/mendel5/alternative-front-ends/commit/fe8c4dac8aa3bd63d6b871acd884932d2558b237
