### ISSUE TITLE
Front-end for Quora.com

### ISSUE THREAD

**Issue by I-Really-Shouldnt-Be-Here** [mendel5/alternative-front-ends#136]
- [Quetre](https://quetre.iket.me/)

- [Instances](https://github.com/zyachel/quetre)

**Comment by Bituvo** [comment]
Was just about to submit this... I see I have been beaten.

**Comment by I-Really-Shouldnt-Be-Here** [comment]
@Bituvo

**Comment by maboroshin** [comment]
Already added. This issue can be closed.
