### ISSUE TITLE
Add yt-local

### ISSUE THREAD

**Issue by ghplpt** [mendel5/alternative-front-ends#14]
Name: yt-local
Site: https://git.sr.ht/~heckyel/yt-local
About: Fork of [youtube-local](https://github.com/user234683/youtube-local), browser-based client written in Python for watching YouTube anonymously and without the lag of the slow page used by YouTube.

**Comment by mendel5** [comment]
Thanks for your contribution!

I just added yt-local.

Commit: https://github.com/mendel5/alternative-front-ends/commit/2549bd11eca54ef028cc02b1cbd3c30423cb62fa
