### ISSUE TITLE
Add SkyTube

### ISSUE THREAD

**Issue by ghplpt** [mendel5/alternative-front-ends#15]
Name: SkyTube
Repository: https://github.com/SkyTubeTeam/SkyTube
About: An open-source YouTube app for Android.

**Comment by mendel5** [comment]
Thanks for your contribution!

I just added SkyTube.

Commit: https://github.com/mendel5/alternative-front-ends/commit/da9a0808e53c765ae60e5ec87b032419ea6a7b30
