### ISSUE TITLE
[Reddit] Android clients: Infinity and Dawn for Reddit

### ISSUE THREAD

**Issue by dm9pZCAq** [mendel5/alternative-front-ends#17]
# Infinity
This is a Reddit client on Android written in Java. It does not have any ads and it features clean UI and smooth browsing experience.
- [src](https://github.com/Docile-Alligator/Infinity-For-Reddit)
- [fdroid](https://f-droid.org/en/packages/ml.docilealligator.infinityforreddit/)

# Dawn for Reddit
Reddit client that is driven by gestures
- [fdroid](https://f-droid.org/en/packages/me.thanel.dank/)

**Comment by mendel5** [comment]
Dawn for Reddit:
- src: https://github.com/Tunous/Dawn
- Forked from: https://github.com/saket/dank

**Comment by mendel5** [comment]
Thanks for your input!
