### ISSUE TITLE
Invidious official domain is now https://invidious.io

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#2]
I suggest changing the URL for the official domain of Invidious from https://invidio.us to https://invidious.io. https://invidio.us is now deprecated as per the [project's recent announcement.](https://github.com/iv-org/invidious/issues/1694) Thank you!

"invidio.us is now deprecated, invidious.io is the new domain.

The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/

https://git.invidious.io/ redirects to the Github page of the project: https://github.com/iv-org/invidious/

https://docs.invidious.io/ redirects to the documentation website of the project: https://github.com/iv-org/documentation/

https://invidious.io/ will become in the future a "project presentation" page (like https://searx.me/ ), we will use a markdown framework like Hugo."

**Comment by mendel5** [comment]
@Mennaruuk Thanks for letting me know! I will update the URL soon.

Btw do you know of any front ends or alternatives to websites, apps, etc. that are not yet included in the overview?
I'm always looking for new projects to add.

**Comment by Mennaruuk** [comment]
Yes! Choose whichever ones you like, I'm sure there are plenty more out there.

- [**CloudTube** ](https://git.sr.ht/~cadence/cloudtube)(a beautiful front-end for Invidious. If search doesn't work, change instance in settings. Right now, for me https://au.ytprivate.com works well)
- **[Invuedious](https://github.com/bocchilorenzo/invuedious)** (another beautiful front-end for Invidious, built with Vue.js)
- **[straw-viewer](https://github.com/trizen/straw-viewer)** (a fork of, and created by the same author of, youtube-viewer. Uses Invidious API)
- **[invidious-viewer](https://github.com/git-bruh/invidious-viewer)** (similar to straw-viewer. Requires MPV player and libmpv.so, provided by Linux distro)
- [**Top of Reddit** ](https://github.com/mgerb/top-of-reddit)(like HNTopLinks but for Reddit)
- **[RedditClient](https://github.com/grey-r/RedditSharp)** (alternative front-end for Reddit, built with Angular)
- [**Libreddit** ](https://libredd.it/)(an alternative front-end for Reddit. Themed around Reddit redesign.)
- **[Updoot](https://github.com/adityam49/Updoot)** (Android, alternative front-end for Reddit)
- **[eddrit](https://github.com/corenting/eddrit)** (alternative front-end for Reddit, inspired by Nitter, built with Python & Starlette)
- **[Shitter](https://github.com/nuclearfog/Shitter)** (Android, alternative front-end for Twitter, built with Java)
- **[Harpy](https://github.com/robertodoering/harpy)** (Android, alternative front-end for Twitter, built with Flutter/Dart)
- **[Twidere X](https://github.com/TwidereProject/TwidereX-Android)** (Android, alternative front-end for Twitter, built mostly with Kotlin, in early stage)
- **[Tweeterr](https://github.com/sherwyn11/Tweeterr)** (tweet from command line)
- **[Tweet.app](https://github.com/rhysd/tweet-app)** (desktop Twitter client that only lets one tweet and they can't see timeline so they can be more productive)
- [**Tweepy** ](https://github.com/tweepy/tweepy)(Twitter for Python)
- **[SlimSocial](https://github.com/rignaneseleo/SlimSocial-for-Facebook)** (Android, alternative front-end for Facebook, built with Java)
- **[fb-messenger-cli](https://github.com/Alex-Rose/fb-messenger-cli)** (use Facebook Messenger from command line)

I want to (sadly) point out that [HNTopLinks ](https://hntoplinks.com)is down. I mentioned the owner about it, I'm uncertain about its coming back up, but I hope it does, seems like a wonderful tool.  Also, I suggest changing the example for Searx, searx.privatenet.cf is not working.

**Comment by mendel5** [comment]
> Yes! Choose whichever ones you like, I'm sure there are plenty more out there.

Thank you very much for this detailed list. I will add these projects to the overview.

I've thought about changing the layout from its current table formatting into a list because many projects don't have an official instance and therefore no examples can be given.

**Comment by Mennaruuk** [comment]
You're welcome!

And yes, not only do sites like Invidious no longer have an official instance, but example sites can go down after a while and are replaced by new ones. Maybe it can look more like the awesome lists (maybe awesome alternative front-ends!?), or put your own spin on it (perhaps categorize by _what_'s being front-ended, so maybe in one column put Facebook and front ends for it, then the new column, then Twitter, then Reddit, then YouTube, and so on and so forth). Or you can categorize by web vs iOS vs Android vs cli. One other thing is maybe you'd like to distinguish links to source code from links to (official) instances. For example, CloudTube has an official instance at https://tube.cadence.moe, but unfortunately it isn't that easy to find it even at sourcehut, and not everyone wants/knows how to self host. One more suggestion is Algolia has a feature like HNTopLinks where you can [sort by last 24 hours for the highest rated links](https://hn.algolia.com/?sort=byPopularity&page=0&dateRange=last24h&type=all). Algolia's HN search is thankfully [open source](https://github.com/algolia/hn-search).

**Comment by mendel5** [comment]
@Mennaruuk Sorry for the delay. I made some changes which you can see here: https://github.com/mendel5/alternative-front-ends/blob/dev001/README.md . The projects/ repos are now grouped by websites.

Do you think there is anything to add or did I forget something? Otherwise I'd push it to the main branch.

**Comment by Mennaruuk** [comment]
Thank you! I think it'd be awesome to add Plumber and ViewTube.

- [Plumber](https://github.com/keshavbhatt/plumber): local and remote video trimmer, can trim parts of video without downloading whole video, utilizes youtube-dl, allows conversion to GIFs
- [ViewTube](https://github.com/ViewTube/viewtube-vue): an alternative front end to YouTube, written in Vue.js, uses Plyr video player; supports SponsorBlock, multiple Invidious instances support, chapters

**Comment by mendel5** [comment]
I just added them. I'll push to main branch, ok?

**Comment by Mennaruuk** [comment]
Wonderful!! Thank you so much

**Comment by mendel5** [comment]
Sure, thanks for your input.

**Comment by mendel5** [comment]
Issue has been resolved with pull request and merge into main branch: https://github.com/mendel5/alternative-front-ends/pull/4
