### ISSUE TITLE
Slide for Reddit

### ISSUE THREAD

**Issue by claudiuskastner** [mendel5/alternative-front-ends#20]
Source:
- Github: https://github.com/ccrama/Slide
- F-Droid: https://f-droid.org/en/packages/me.ccrama.redditslide/

**Comment by mendel5** [comment]
Thanks for your input, @claudiuskastner !

I've added Slide for Reddit here: https://github.com/mendel5/alternative-front-ends/commit/89bf309cd8cb41051e530b4d325f0e295be2c911
