### ISSUE TITLE
Wikiless for Wikipedia

### ISSUE THREAD

**Issue by gripped** [mendel5/alternative-front-ends#21]
Wikiless for Wikipedia

https://codeberg.org/orenom/wikiless

**Comment by mendel5** [comment]
Hi @gripped , thanks for your input!

I've added Wikiless for Wikipedia here: https://github.com/mendel5/alternative-front-ends/commit/31c7e0ab3f0453b2ec1e64c215c466ecff0e2067

**Comment by shivanshu-semwal** [comment]
The codeberg link is not working

<https://github.com/Metastem/wikiless> this works
