### ISSUE TITLE
Nitter is discontinued

### ISSUE THREAD

**Issue by ghost** [mendel5/alternative-front-ends#219]
Recently this week the Twitter frontend, Nitter, has been discontinued.
https://alternativeto.net/news/2024/1/privacy-oriented-x-front-end-nitter-is-shutting-down-following-changes-to-guest-accounts/

**Comment by ayoahha** [comment]
Yes !
So sad

**Comment by cRu572Vltn** [comment]
> Yes ! So sad

There are other instances still working

**Comment by pgmtx** [comment]
> There are other instances still working

According to [twiiit.com](https://twiiit.com/), only two instances are online, but privacydev's one is rate limited, and [that one](https://nitter.esmailelbob.xyz/) only works halfway (you may see tweets from a user but not the answers or the tweets retweeted by the user).

So yes, Nitter is dead, and the official website is unreachable.

**Comment by meatspinner** [comment]
esmailelbob's instance RSS still works, though its sporadic.

**Comment by ghost** [comment]
Can't really find an alternative I can use in a web browser, can only see a bunch of Android clients when searching around.
