### ISSUE TITLE
Add imgin for Imgur

### ISSUE THREAD

**Issue by bkqtnte10** [mendel5/alternative-front-ends#26]
It is not finished and currently only works for albums but:

https://git.voidnet.tech/kev/imgin

**Comment by ltGuillaume** [comment]
I'm afraid this project might be dead. It's official instance has been returning 502 errors for quite some time now and all commits to the project have been made within a week, after which nothing happened for months.

**Comment by mendel5** [comment]
I have just accessed the official instance and it seemed to work again.

**Comment by ltGuillaume** [comment]
Yes, I saw it working yesterday, too, although it still doesn't with GIFs or videos. It's on the roadmap, but without any activity for several months, I'm not optimistic.

**Comment by mendel5** [comment]
Maybe you can fork it and add the features you are missing? 😅
