### ISSUE TITLE
Barinsta is gone

### ISSUE THREAD

**Issue by jnv** [mendel5/alternative-front-ends#28]
Unfortunately link to Barinsta repo 404s, the author received cease and desist by Facebook: https://github.com/austinhuang0131/austinhuang0131/issues/2

**Comment by mendel5** [comment]
A comment was also added to the repo: https://github.com/mendel5/alternative-front-ends/commit/254d8171eb839487bd00ae2e35443ae282e59b4f

**Comment by jnv** [comment]
Thanks @mendel5! I will close this issue since my concern was addressed.

**Comment by mendel5** [comment]
Thanks for your feedback!
