### ISSUE TITLE
Alternative reddit frontend

### ISSUE THREAD

**Issue by Doosty** [mendel5/alternative-front-ends#30]
Hi, i see you dont have it listed, and i really like this one: https://github.com/junipf/reddit-frontend

**Comment by ltGuillaume** [comment]
FYI, as far as I can see, there are no privacy benefits to this front-end: it still needs your browser to connect directly to reddit.com.

**Comment by mendel5** [comment]
Thanks for your comments.
Unfortunately the linked Reddit front-end does not load in Mozilla Firefox, however it loads in Google Chrome. It also hasn't been updated since March 2020.

**Comment by mendel5** [comment]
I still decided to add the project to the repo. Maybe someone forks it or wants to have a look at the code.

See commit here: https://github.com/mendel5/alternative-front-ends/commit/f2ede5a45d1efba54c7bf97f0bc0c972130c5c78
