### ISSUE TITLE
Add outline.com

### ISSUE THREAD

**Issue by ImportTaste** [mendel5/alternative-front-ends#31]
https://outline.com/

I'm not sure if this project would qualify. It's more of an indirect alternative front-end than a direct one. You supply it an article from one of many, many different websites, and it does its best to take the main content and give it a nice, clean page format.

I especially like using this for when I want to share a news article, but it can handle things like step-by-step tech support blogs as well (since most of them just use Wordpress, which it knows how to parse).

**Comment by mendel5** [comment]
Thanks for your input! I know outline.com and sometimes use it myself.
As far as I know the source code of outline.com is not available as free/open-source. I try to only add free/open-source projects to this repo.
However, I also like to provide value to other people with my work and if people think outline.com is useful then maybe we have to do an exception. I will think about it...

**Comment by mendel5** [comment]
I just added Outline.com to the list. See: https://github.com/mendel5/alternative-front-ends/commit/6068ea3132d85cbb95c7e45ac853846ba0b28c4e

However, I also added a note that the source code of Outline.com is not available under a free/open-source license.
