### ISSUE TITLE
Add Haxplore for HackerNews

### ISSUE THREAD

**Issue by htadashi** [mendel5/alternative-front-ends#35]
[Haxplore](https://haxplore.com/) is alternative frontend for HN with many keyboard shortcuts.

**Comment by mendel5** [comment]
Thanks for your input, @htadashi .

Haxplore was already mentioned in this pull request: https://github.com/mendel5/alternative-front-ends/pull/25

It seems that Haxplore is a proprietary service and its source code is not available to the public under a free license. If you know where I can find the source code, please let me know.

**Comment by htadashi** [comment]
Hi @mendel5. My bad, I didn't notice the other PR and that you were listing only open-source front-ends.
To the best of my knowledge, Haxplore is not open-source. 

I'll let you know if I discover something.

**Comment by mendel5** [comment]
Sure, thanks for your quick response, @htadashi !
