### ISSUE TITLE
Add rajatkulkarni95/hckrnws for Hacker News

### ISSUE THREAD

**Issue by rajatkulkarni95** [mendel5/alternative-front-ends#36]
Self Plug:
Site - https://hckrnws.com
Repo - https://github.com/rajatkulkarni95/hckrnws

**Comment by mendel5** [comment]
Thanks for your input, @rajatkulkarni95 !

Your project has been added. See commit: https://github.com/mendel5/alternative-front-ends/commit/bf6f5acece2077d826cca6064af1778e7ef92981
