### ISSUE TITLE
Add TubeSync for Youtube

### ISSUE THREAD

**Issue by sildur** [mendel5/alternative-front-ends#38]
https://github.com/meeb/tubesync

From their README:
> TubeSync is a PVR (personal video recorder) for YouTube. Or, like Sonarr but for YouTube (with a built-in download client). It is designed to synchronize channels and playlists from YouTube to local directories and update your media server once media is downloaded.

**Comment by mendel5** [comment]
Thanks for your input, @sildur !

TubeSync for Youtube has been added. See commit: https://github.com/mendel5/alternative-front-ends/commit/6f5c922bd85bed9848dd65b0e2ebdba1d1483970
