### ISSUE TITLE
Add Premii.com for Hacker News and Reddit

### ISSUE THREAD

**Issue by fdoyon** [mendel5/alternative-front-ends#42]
reddit: https://reddit.premii.com
hn: https://hn.premii.com

I am not the author, just a user.

**Comment by mendel5** [comment]
Original title: `Premii : alternative HN and Reddit (closed-source)`

**Comment by mendel5** [comment]
Hi @fdoyon , thanks for your input!

As you already mentioned Premii.com is a proprietary service and closed-source. Therefore it unfortunately cannot be added to the list. If Premii becomes open-source then please let me know!
