### ISSUE TITLE
Add Android app 'UntrackMe' (nitterizeme), similar to 'Privacy Redirect'

### ISSUE THREAD

**Issue by linuxissuper** [mendel5/alternative-front-ends#45]
Android app to transform links system wide.
`UntrackMe transforms Twitter, YouTube, Instagram, Reddit and Medium and Wikipedia links to links of open source, privacy friendly front-ends.`   
   
https://framagit.org/tom79/nitterizeme

**Comment by mendel5** [comment]
Thanks for your input, @linuxissuper !

The Android app nitterizeme / UntrackMe has already been added to the list.

See pull request https://github.com/mendel5/alternative-front-ends/pull/49 and commit https://github.com/mendel5/alternative-front-ends/commit/260130bf7d6ec17915dae4b957c75816da143121 .
