### ISSUE TITLE
Add Spot for Spotify

### ISSUE THREAD

**Issue by phillipprado** [mendel5/alternative-front-ends#48]
[Spot](https://github.com/xou816/spot): Gtk/Rust native Spotify client for the Linux desktop. It requires a premium acccount.

**Comment by mendel5** [comment]
Thanks for your input, @phillipprado !

Spot has been added. See commit: https://github.com/mendel5/alternative-front-ends/commit/abe6f39a845ce5410876373286b6495a32ca4df0
