### ISSUE TITLE
Is there any alternative front-end for Twitch?

### ISSUE THREAD

**Issue by supng** [mendel5/alternative-front-ends#50]
Been looking but can only find extensions for the actual site :(

Thanks for your compilation.

**Comment by mendel5** [comment]
Hi @supng , thanks for reaching out. You are looking for an alternative front-end for Twitch.tv.

I am aware of these two projects:
- https://github.com/streamlink/streamlink-twitch-gui
- https://github.com/oscartbeaumont/ElectronPlayer

However, I haven't tested them yet. Maybe you can test one or both of them and give us a feedback?

**Comment by gelaechter** [comment]
[mpv Media Player](https://github.com/mpv-player/mpv) accepts Twitch streams.
But playing the stream really is all it does.

**Comment by mendel5** [comment]
Hi @supng , there is now a section for alternative front-ends for Twitch:
- https://github.com/mendel5/alternative-front-ends#twitch
