### ISSUE TITLE
Enhance the Imgur section

### ISSUE THREAD

**Issue by TheFrenchGhosty** [mendel5/alternative-front-ends#56]
Rimgo https://codeberg.org/video-prize-ranch/rimgo is the maintained frontend, that everyone moved to, made by the guy behind Librarian (an Odysee frontend) https://codeberg.org/librarian/librarian

Imgin and rimgu are both dead.

**Comment by mendel5** [comment]
Hi @TheFrenchGhosty , thanks for your suggestion. I have added Rimgo with this commit: https://github.com/mendel5/alternative-front-ends/commit/e43ffd644c5d6ef9b5a43f05b9fc6b80fcb5710c .

> Imgin and rimgu are both dead.

How do you know that?

Reference:
- https://git.voidnet.tech/kev/imgin/commits/branch/master
- https://codeberg.org/3np/rimgu/commits/branch/master

**Comment by TheFrenchGhosty** [comment]
>How do you know that?

https://git.voidnet.tech/kev/imgin/commits/branch/master no commits from the author for 4 months

https://codeberg.org/3np/rimgu/commits/branch/master no commits from the author for 2 months + doesn't merge PRs

**Comment by mendel5** [comment]
> no commits from the author for X months

I understand what you mean. However, we don't know about the maintainers' situation and maybe they are busy with other things.

For the time being I would like to keep Imgin and Rimgu included in the overview. Maybe another person will fork their repo and improve it.
