### ISSUE TITLE
Barinsta for Instagram: Fork available on codeberg.org

### ISSUE THREAD

**Issue by Technetium1** [mendel5/alternative-front-ends#58]
Not unmaintained, just moved: https://codeberg.org/avalos/barinsta

**Comment by mendel5** [comment]
Thank you for your contribution, @Technetium1 !

The linked repository has been added to the list: https://github.com/mendel5/alternative-front-ends/commit/bb143cfaae45ea3f5b583ac893ef603bebc4d14a

**Comment by Technetium1** [comment]
@mendel5 this seems accurate, please update the link.

**Comment by davidgram505-droid** [comment]
That’s a tough exit, but I completely respect your decision to prioritize your own privacy and peace of mind over forcing motivation for a platform you no longer use. Honest dev updates like this are rare, so don't beat yourself up over unfulfilled goals—you gave it a solid shot and leaving the repo public is a great gift to the open-source community. If anyone still needs to mock up posts or layouts without actually using Meta's ecosystem, tools like [fakeinstapost.com/](https://fakeinstapost.com/) are pretty handy for quick visuals. Wishing you all the best with whatever project you tackle next!
