### ISSUE TITLE
Add Beatbump for YouTube Music

### ISSUE THREAD

**Issue by IronMaltese** [mendel5/alternative-front-ends#62]
Add [Beatbump](https://github.com/snuffyDev/Beatbump) as it is an alternative to YouTube music, and maybe even make a separate section to differentiate YouTube and YouTube Music

**Comment by mendel5** [comment]
https://github.com/snuffyDev/Beatbump

**Comment by mendel5** [comment]
Thanks for your contribution, @IronMaltese !

Beatbump has been added to the overview with this commit: https://github.com/mendel5/alternative-front-ends/commit/421d52999062f79eca7fa186d9777e8a838bbcaa
