### ISSUE TITLE
Add Libredirect for redirection

### ISSUE THREAD

**Issue by IronMaltese** [mendel5/alternative-front-ends#63]
Add [Libredirect](https://github.com/libredirect/libredirect) to redirectors, as it is an actively maintained fork of Privacy Redirect

**Comment by mendel5** [comment]
https://github.com/libredirect/libredirect , fork of https://github.com/SimonBrazell/privacy-redirect

**Comment by mendel5** [comment]
Thanks for your contribution, @IronMaltese !

Libredirect has been added to the overview with this commit: https://github.com/mendel5/alternative-front-ends/commit/421d52999062f79eca7fa186d9777e8a838bbcaa
