### ISSUE TITLE
Add kallist/kddit-spaghetti for Reddit

### ISSUE THREAD

**Issue by takoyaki99** [mendel5/alternative-front-ends#66]
[kddit.kalli.st](https://kddit.kalli.st/) is another site to use for reddit, it's relatively minimal but works quite well IMO.

**Comment by eatb33ts** [comment]
I was able to find the source code for kddit at https://git.kalli.st/kallist/kddit-spaghetti

**Comment by mendel5** [comment]
This issue was fixed with this pull request: https://github.com/mendel5/alternative-front-ends/pull/67

**Comment by mendel5** [comment]
Thank you for your contributions, @takoyaki99 and @eatb33ts .

This issue was fixed with this pull request: https://github.com/mendel5/alternative-front-ends/pull/67
