### ISSUE TITLE
Add HookedBehemoth/supreme-waffle (renamed to "Neuters") for Reuters.com

### ISSUE THREAD

**Issue by HookedBehemoth** [mendel5/alternative-front-ends#68]
I made an alternative frontend for the news website [Reuters.com](https://reuters.com/) and I host it under [Boxcat.site](https://boxcat.site/about). It's mostly meant to be used with link redirects and the home page isn't really usable.
Code is here: https://github.com/HookedBehemoth/supreme-waffle.

I'm not quite sure in what category that would fit or if it should go in it's own.

**Comment by mendel5** [comment]
Very nice! Thank you for creating this project, @HookedBehemoth .

I added your project in a new section called "Reuters", see https://github.com/mendel5/alternative-front-ends#reuters .

**Comment by mendel5** [comment]
The repo HookedBehemoth/supreme-waffle was renamed to HookedBehemoth/neuters:
- https://github.com/HookedBehemoth/neuters/issues/2
