### ISSUE TITLE
Silkky

### ISSUE THREAD

**Issue by mendel5** [mendel5/alternative-front-ends#7]
Hi @TheSilkky !

I saw your Reddit post here: [https://old.reddit.com/r/opensource/comments/n8782f/i_am_hosting_free_opensource_privacy_respecting/](https://old.reddit.com/r/opensource/comments/n8782f/i_am_hosting_free_opensource_privacy_respecting/), linking to your website at [https://silkky.cloud/](https://silkky.cloud/). Thank you for posting this.

I will add these projects to my repo.

**Comment by TheSilkky** [comment]
Thanks I really appreciate this.

**Comment by mendel5** [comment]
Sure!

Commits:
- [Libreddit](https://github.com/mendel5/alternative-front-ends/commit/e5d5e49a54a73640b97568e1a6b2fc9d7f8f7be2)
- [PrivateBin](https://github.com/mendel5/alternative-front-ends/commit/250c47e3b1f781308f4eb223290e7666a414ca6d)
- [Matrix Synapse](https://github.com/mendel5/alternative-front-ends/commit/9c9f3fcf7b3a6e347b9936723510f6813d360447)
- [vaultwarden and snapdrop](https://github.com/mendel5/alternative-front-ends/commit/adf0ea7bc64f4169e06c28d8b86a1b57c1d15dc9)
- [hedgedoc, etherpad and gitea](https://github.com/mendel5/alternative-front-ends/commit/78f180e5df0b889abb97800983f097d76c82e3b1)

**Comment by mendel5** [comment]
Done :heavy_check_mark:
