### ISSUE TITLE
Add th-ch/youtube-music for YouTube Music

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#70]
**YouTube Music (by th-ch)**: Powered by community-made plugins ranging from MP3 downloader, ad blocker, audio compressor, and autoplay disabler to lyrics support, playback speed changer, and support for Last.fm as well as Discord’s [Rich Presence](https://discord.com/rich-presence).

https://github.com/th-ch/youtube-music

**Comment by mendel5** [comment]
Thank you for your contribution, @Mennaruuk !

th-ch/youtube-music has been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/3273974869755cb20ad5e3014582c9e69db60f9a
