### ISSUE TITLE
Add SearXNG as a metasearch engine

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#71]
**SearXNG**: A fork of SearX focused on providing better theming, more translations, detailed descriptions of search engines and their reliabilities, and easier bug reporting.

Full list of changes: https://github.com/searxng/searxng/wiki/Changes-from-version-1.0.0

Repo: https://github.com/searxng/searxng

(Note that instance directory for SearXNG is same as SearX’s: [searx.space](https://searx.space).)

**Comment by mendel5** [comment]
Thanks for your contribution, @Mennaruuk !

SearXNG has been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/62a07bf1d661e2b4a616ca92d72537a7f9c53114
