### ISSUE TITLE
Add spotube, SpotX, kotify, librespot for Spotify

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#72]
- [spotube](https://github.com/KRTirtho/spotube): Cross-platform Spotify client that uses YouTube to stream music and has no ads

- [SpotX](https://github.com/amd64fox/SpotX): Windows-only Spotify client that blocks ads and unlocks skip function

Additionally, there are [kotify ](https://github.com/dzirbel/kotify)and [librespot](https://github.com/librespot-org/librespot), but I don't think they cater to a general audience (kotify is for power users focused on library organization, librespot is for premium users only).

**Comment by eatb33ts** [comment]
Thank you for the suggestions @Mennaruuk ! I have added them all to #85 with a note on the latter two about account requirements.

**Comment by mendel5** [comment]
The projects spotube, SpotX, kotify and librespot have been added with https://github.com/mendel5/alternative-front-ends/pull/85 .

Thanks for your contribution, @Mennaruuk and @eatb33ts .
