### ISSUE TITLE
Add Omgur and imgrs for Imgur

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#73]
[omgur](https://github.com/geraldwuhoo/omgur): Another self-hosted frontend for imgur written in Go. Like all the others, it has a Dockerfile.

**Comment by Mennaruuk** [comment]
@eatb33ts Thanks for the PR! Can you also please add imgrs? It's a Rust rewrite of omgur, released just five days ago.

https://github.com/geraldwuhoo/imgrs

**Comment by mendel5** [comment]
imgrs has been added as well:
- Commit: https://github.com/mendel5/alternative-front-ends/commit/84732342eac5b8a746e112c5995269bce12efd6a
- https://github.com/geraldwuhoo/imgrs
- https://git.geraldwu.com/gerald/imgrs

Thanks, @Mennaruuk !
