### ISSUE TITLE
Add LibreX for search engines

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#74]
[LibreX](https://github.com/hnhx/librex): a very small and simple meta search engine, fetches and anonymizes results from Google only, has API support, allows redirects to Invidious/Bibliogram/Nitter/Libreddit

![image](https://user-images.githubusercontent.com/52135169/158080227-223ca5cf-c124-41f9-bf5b-cee747b864b0.png)

**Comment by mendel5** [comment]
Thanks for your contribution, @Mennaruuk !

LibreX has been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/a000f91c81f3e3f05c7831a7d0e372d8c2cd2367
