### ISSUE TITLE
Add streamlink-twitch-gui, Twire, Xtra, ElectronPlayer for Twitch

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#75]
[streamlink-twitch-gui](https://github.com/streamlink/streamlink-twitch-gui): Requires login, but it works very well, streams via streamlink to VLC

[Twire](https://github.com/twireapp/Twire): Twitch client for Android, supports VODs with chat replay, custom emotes (BTTV and FFZ) and Picture in Picture mode

   - [Twire seems to require log in to work](https://github.com/twireapp/Twire/issues/314#issuecomment-1047945300), a limitation of Twitch's new API called Helix. 

[Xtra](https://github.com/crackededed/Xtra): Twitch player for Android

I tried [ElectronPlayer](https://github.com/oscartbeaumont/ElectronPlayer). It has the same concept as the wrappers for YouTube. So it's essentially a browser wrapper around Twitch.com that blocks ads among other features. Also, it only supports Linux and macOS at the moment, with the Linux version last released in February 2020.

**Comment by mendel5** [comment]
Thanks for your contribution, @Mennaruuk !

The projects streamlink-twitch-gui, Twire, Xtra and ElectronPlayer have been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/749d4f6f6d46904ffd579f496885079e170c5323
