### ISSUE TITLE
Add Librarian for Odysee.com

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#76]
[Librarian](https://codeberg.org/librarian/librarian/): alternative frontend for Odysee

([Official instance](https://librarian.bcow.xyz/))

**Comment by mendel5** [comment]
Thanks for your contribution, @Mennaruuk !

The project Librarian has been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/668930569c7cd2c96362e75f92f5ac507c3e615a
