### ISSUE TITLE
Add LibreTube, BlackHole, oleksis/youtube-dl-gui for YouTube

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#77]
[LibreTube](https://github.com/libre-tube/LibreTube): Android frontend for YouTube, based on Piped

[BlackHole](https://github.com/Sangwan5688/BlackHole): Android frontend for YouTube Music/Spotify

[youtube-dl-gui](https://github.com/oleksis/youtube-dl-gui): Cross platform YouTube downloader

   - The one currently in the list by jely2002 is also called youtube-dl-gui, but it has a new name: Open Video Downloder

**Comment by mendel5** [comment]
Thank you for your contribution, @Mennaruuk !

The projects LibreTube, BlackHole and oleksis/youtube-dl-gui have been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/9030d8efcf1cbaac302261261175ace54ebf5e14
