### ISSUE TITLE
Add SongRec for Shazam

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#78]
[SongRec](https://github.com/marin-m/SongRec): An alternative cross platform frontend for Shazam

![image](https://user-images.githubusercontent.com/52135169/158094920-0381f660-da7c-4133-9a50-43c15ab62356.png)

**Comment by mendel5** [comment]
Thank you for your contribution, @Mennaruuk !

The project SongRec has been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/83487ef8cf61540546bee4fd6a4cf44035894980
