### ISSUE TITLE
Add Fritter

### ISSUE THREAD

**Issue by SuperSonicHub1** [mendel5/alternative-front-ends#8]
Fritter is an alternative frontend to Twitter for Android  and iOS written in Flutter and Dart: https://github.com/jonjomckay/fritter

**Comment by mendel5** [comment]
Just added it, see https://github.com/mendel5/alternative-front-ends/commit/e700e4dfb112f1516a0ef1426b21e0632a05db5e .
Thanks for the suggestion!

**Comment by SuperSonicHub1** [comment]
No problem.

>
