### ISSUE TITLE
Add multiple frontend clients for Mastodon

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#80]
- [Pinafore](https://github.com/nolanlawson/pinafore): an alternative web client for Mastodon focused on speed and efficiency

https://user-images.githubusercontent.com/52135169/158148371-fbb9a6c7-bd21-4646-a117-1dd4a3f03202.mp4

- [Mercury](https://onmercury.app/): a customizable client for the Mastodon for iOS
- [Sengi](https://nicolasconstant.github.io/sengi/): a cross platform FLOSS multi-account Mastodon desktop client
- [TheDesk](https://github.com/cutls/TheDesk): a cross platform Mastodon desktop client, made with love in Japan
- [Tootle](https://github.com/bleakgrey/tootle): a simple Mastodon client for Linux
- [Tusky](https://tusky.app/): a lightweight Mastodon client for Android
- [Fedilab](https://framagit.org/tom79/fedilab): a multi-account Mastodon client for Android
- [Hyperspace](https://hyperspace.marquiskurt.net/): a cross platform Mastodon client that looks like eye candy 🍬

**Comment by mendel5** [comment]
Hi @Mennaruuk , can you open a pull request that includes a new section for Mastodon projects and add the projects listed in your comment?

**Comment by Mennaruuk** [comment]
Yes I will do it today!!

**Comment by mendel5** [comment]
- Pinafore: https://github.com/nolanlawson/pinafore
- Mercury: https://onmercury.app
- Sengi: https://nicolasconstant.github.io/sengi
- TheDesk: https://github.com/cutls/TheDesk
- Tootle: https://github.com/bleakgrey/tootle
- Tusky: https://tusky.app
- Fedilab: https://framagit.org/tom79/fedilab
- Hyperspace: https://hyperspace.marquiskurt.net

**Comment by mendel5** [comment]
Thank you, @Mennaruuk ! I couldn't find a repository for the source code of Mercury. Do you maybe know where to find it?

**Comment by Mennaruuk** [comment]
Mercury is most likely closed source. Everything else looks great!

**Comment by mendel5** [comment]
Thank you for your contribution, @Mennaruuk !

The issue has been resolved by merging this pull request: https://github.com/mendel5/alternative-front-ends/pull/89
