### ISSUE TITLE
Add Crow Translate for Google Translate

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#81]
[Crow Translate](https://crow-translate.github.io/): A simple and lightweight cross platform translator that allows translation using LibreTranslate, Lingva, Google, Bing, and Yandex, as well as text-to-speech using Google.

![image](https://user-images.githubusercontent.com/52135169/158160364-3b383bea-e4df-4fce-9960-6263cb894d2b.png)

**Comment by mendel5** [comment]
https://github.com/crow-translate/crow-translate

**Comment by mendel5** [comment]
Thank you for your contribution, @Mennaruuk !

The project Crow Translate has been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/a3983ed2c14f41539ca9913e828c14a4fe1b4d43
