### ISSUE TITLE
Add Albatross for Twitter

### ISSUE THREAD

**Issue by Mennaruuk** [mendel5/alternative-front-ends#83]
[Albatross](https://play.google.com/store/apps/details?id=com.nick.mowen.albatross): an ad-free, effortless Twitter client for Android designed in Material
![image](https://user-images.githubusercontent.com/52135169/158168085-ea4e8d2d-6f08-4ef9-8d28-5f492f96c3e7.png)

**Comment by mendel5** [comment]
Do you know if the source code of Albatross is available under a free/libre and open source license? If yes, I'd appreciate if you can post the link to the repository. Thank you!

**Comment by Mennaruuk** [comment]
Unfortunately, it seems like the app is closed source. Bummer 🤦🏻‍♂️. I’ll be closing. Thanks for your consideration, @mendel5 !

**Comment by mendel5** [comment]
No worries!
